basic:
    name: 'https://expeditiondental.com/'
    environments:
        production: 'https://expeditiondental.com/'
        staging: 'https://expd.bebright2024.skybox4.com/'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /request-an-appointment
        - /services/emergency-services
        - /professional-referrals
        - /locations
        - /locations/nixa
        - /locations/republic
        - /locations/springfield
        - /services
        - /services/pediatric-dentistry
        - /services/pediatric-dentistry/infant-exam
        - /services/pediatric-dentistry/preventative-care
        - /services/pediatric-dentistry/preventative-care/dental-exams-cleanings
        - /services/pediatric-dentistry/preventative-care/fluoride-treatments
        - /services/pediatric-dentistry/preventative-care/sealant-for-teeth
        - /services/pediatric-dentistry/restorative-care
        - /services/pediatric-dentistry/restorative-care/tooth-extractions
        - /services/pediatric-dentistry/restorative-care/fillings-restorations
        - /services/pediatric-dentistry/restorative-care/pulpotomies-root-canals
        - /services/orthodontics
        - /services/orthodontics/braces
        - /services/orthodontics/clear-aligners
        - /services/orthodontics/retainers
        - /services/orthodontics/night-guards
        - /services/diagnostic-services
        - /services/diagnostic-services/digital-x-rays
        - /services/diagnostic-services/diagnostic-imaging
        - /services/specialized-treatments
        - /services/specialized-treatments/sedation-dentistry
        - /services/specialized-treatments/sports-dentistry
        - /about-us
        - /about-us/what-sets-us-apart
        - /about-us/our-doctors
        - /about-us/our-team
        - /about-us/careers
        - /about-us/contact-us
        - /your-visit
        - /your-visit/new-patients
        - /your-visit/financial-insurance-information
        - /your-visit/pediatric-faqs
        - /your-visit/orthodontics-faqs
        - /resources
        - /privacy-policy
        - /accessibility-statement
        - /opt-out-preferences
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 10
    scroll: false
    headers: {  }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: {  }
    sensitivity: 30
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: '10'
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
